package com.app;

import java.io.FileNotFoundException;
import java.io.PrintWriter;

public class ExceptionHandling {

	public static void main(String[] args) throws FileNotFoundException {

		try {
			System.out.println("Statement 1");
			System.out.println("Statement 2");
//			int res = 10 / 0;
//			return;
			System.out.println("Statement 3");

		} catch (NullPointerException e) {
			System.out.println("inside catch block Cause of Exception : " + e.getMessage());

		} finally {
			System.out.println("Inside finally block");
		}

		System.out.println("Outside try-catch block");

		PrintWriter pw = new PrintWriter("");

	}

}
